on:
  pull_request:
    types: [opened]

# https://dev.to/scienta/get-changed-files-in-github-actions-1p36
jobs:
  changedFiles: 
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      js: ${{ steps.changes.outputs.js }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changes
        run: |
          echo "::set-output name=js::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .js$ | xargs)"
  lint:
      runs-on: ubuntu-latest
      # require the first job to have ran
      needs: changedFiles
      # only run there are changed files
      if: ${{needs.changedFiles.outputs.js}}
      steps:
        - name: echo changed files
          run: echo ${{needs.changedFiles.outputs.js}}
