on:
  pull_request:
    types: [opened]

jobs:
  changedFiles: 
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      js: ${{ steps.changes.outputs.js }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changes
        run: |
          echo "::set-output name=js::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -l "/* eslint-disable */" | xargs)"
  comment:
      runs-on: ubuntu-latest
      # require the first job to have ran
      needs: changedFiles
      # only run there are changed files
      if: ${{needs.changedFiles.outputs.js}}
      steps:
        - name: echo changed files
          run: echo ${{needs.changedFiles.outputs.js}}
        - name: Create comment
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'eslit-disable has been found in the following files: ${{needs.changedFiles.outputs.js}}''})
        - name: block pull request
          run: |
            exit 1
  
